version: "1.0"
info:
  model: int-scaffold
packages:
- name: DemosalesProject
  gitServerName: KritikasGitHubAccount
  gitUrl: https://github.com/KitNabber/DemosalesProject
  gitUsername: KitNabber
  gitBranch: main
- name: OpenWeatherClient
  gitServerName: KritikasGitHubAccount
  gitUrl: https://github.com/rahuldemocenter
  gitUsername: KitNabber
  gitBranch: main
services:
- serviceName: project.demosales.integrations:testapp
  packages:
  - name: DemosalesProject
    version: "1.0"
  - name: OpenWeatherClient
    version: "1.0"
- serviceName: OpenWeatherClient.REST.openweatherclient_.services:CurrentWeatherData
  packages:
  - name: OpenWeatherClient
    version: "1.0"
- serviceName: pub.client:http
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: pub.json:jsonStreamToDocument
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: pub.json:documentToJSONString
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
configurationVariables:
  jdbc.jdbcTestPool.waitingThread: "0"
  jdbc.jdbcTestPool.minConns: "0"
  jdbc.jdbcTestPool.expireTime: "60000"
  jdbc.jdbcTestPool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/jdbcTestPool.log;ddtdbg.ProtocolTraceShowTime=true
  jdbc.jdbcTestPool.maxConns: "10"
  jdbc.jdbcTestPool.userid: root
  jdbc.jdbcTestPool.driverAlias: MySQL Database Java Connector Driver
  jdbc.jdbcTestPool.spyenabled: "false"
  jdbc.jdbcTestPool.snoopenabled: "false"
  jdbc.jdbcTestPool.password: "{AES}er+I3U8nDVm8F4DBRST1+A=="
  jdbc.jdbcTestPool.spyparms: SpyAttributes=(log=(file)logs/spy/jdbcTestPool.log;logTName=yes;timestamp=yes)
  jdbc.jdbcTestPool.dbURL: jdbc:mysql://mysql.test.local:3306/webm
  jdbc.jdbcTestPool.poolThreshold: "0"
  jdbc.jdbcTestPool.useSSL: "false"
